name: ummat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^4.3.2+2
  fluttertoast: ^7.0.4
  intl_phone_field: ^1.4.2
  pin_entry_text_field:
  http_auth:
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.3+1
  firebase_messaging: ^7.0.3
  cloud_functions: ^0.7.2
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.3
  shared_preferences: ^0.5.12+4
  geolocator: ^6.1.14
  intl: ^0.16.1
  random_string: ^2.0.0
  flutter_native_timezone: ^1.0.4
  ntp: ^1.0.7
  path_provider: ^1.6.24
  path: ^1.6.0
  progress_dialog: ^1.2.2
  dio: ^3.0.9
  http: ^0.12.0+2
  data_connection_checker: ^0.3.4
  connectivity: ^2.0.2
  file_picker: 1.4.3+1
  cached_network_image: 2.3.3
  pinch_zoom_image_last: ^0.3.2
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.7.0
  dropdown_formfield: ^0.1.1
  flutter_sound: ^7.7.0+1
  video_player: ^1.0.0
  video_thumbnail: ^0.1.6
  flutter_video_info: ^1.0.1
  percent_indicator: ^2.1.5
  image_picker: ^0.6.7+4
  carousel_pro: 1.0.0
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.10
  simple_url_preview: ^0.1.2
  local_auth: ^0.6.3+4
  diacritic: ^0.1.1
  sentry: ^2.2.0
  launch_review: ^2.0.0
  photo_view: ^0.4.0
  contacts_service: ^0.2.4
  chewie: ^0.12.0
  jiffy: ^2.1.1
  localstorage: ^3.0.6+9
  mime: ^0.9.6+2
  permission_handler: ^3.0.0
  overlay_support: ^1.0.5
  scoped_model: ^1.0.1
  universal_platform: ^0.1.3
  dotted_border: ^1.0.7
  app_settings: ^4.0.4
  giphy_client: ^0.2.0
  share: ^0.6.1
  crypto: ^2.0.6
  encrypt: ^3.0.0
  flutter_secure_storage: ^3.3.1+1
  package_info: ^0.4.0+13
  admob_flutter: ^1.0.1
  agora_rtc_engine: ^3.2.1
  firebase_dynamic_links:
    git:
      url: https://github.com/mrmilu/flutterfire
      path: packages/firebase_dynamic_links
      ref: firebase_dynamic_links





dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_driver:
    sdk: flutter
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
